---
title: "`learnr` Interactives or: How I Learned to Stop Worrying and Turn my Students into Pixelated Farmers"
output: html_notebook
---

Hi folks,

My part of today is called **`learnr` Interactives or: How I Learned to Stop Worrying and Turn my Students into Pixelated Farmers**.

Now, I've started well by completely lying to you. I have most certaintly not managed to stop worrying and only a few of my students turned into pixelated farmers. But what I wanted to share today was my experience with leveraging my R and RMarkdown skills to be able to create easy to deploy interactive tutorials and class activities for learners, all while getting to lean in to the creative silliness that has either been what is keeping me sane through the pandemic, or the best evidence of my insanity.

You can access my slides directly [here](https://bolton-cds-w22.netlify.app/#1), but I will also pop any relevant links in chat.



Students engage with __asynchronous activities__ at the times and in the ways that suit them best, BEFORE synchronous activities.

## Image descriptions
### Slide 1

Background image is a gif from Dr Strangelove (1964, black and white) of a man waving a cowboy hat and riding a large nuclear bomb that is being dropped out of a plane onto the landscape below.

### Slide 3

A pixel art based image of a farm surrouned by fences, crops and trees, including two people avatars, one rifing a horse and one carrying corn. This is an image from the [Stardew Valley game](https://www.stardewvalley.net/). Pixel art text made to look like boards of raw wood (with leafy offshoots) are nailed together to form the words "STATDEW VALLEY". The second 't' in STAT is slightly tilted towards the right while all the others or oriented up and down (to draw attention to it not saying STARDEW).

### Slide 5

Pixelated image of me (Liza) a smiling brunette, with a light skin-tone and feminine presenting. Image was manipulatedfrom an original photo to be pixelated using tools in R.

### Slide 6

Background image is a gif from Dr Strangelove (1964, black and white) of a two men grappling (the one in front is in a large black coat and black hat, while the one behind is in a suit). ANother man, bald and in classes approaches from the right of the and addresses them, causing them both to pause. He says "Gentleman. You can't fight in here. This is the War Room!"

### Slide 12

A poorly drawn cartoon of a bao with legs and arms, in a pink ballerina outfit, with roses thrown at its feet and the text 'bao take a bow' at the top right

### Slide 13

A process flow diagram with 4 sections. 

- __Plan__: Plan activity based on learning outcomes: commentary, coding tasks, question prompts.  
- __R__:Combine code, commentary, hints, questions, etc., in an RMarkdown document (learnr package).  
- __GitHub__: Push to GitHub (check out GitHub desktop and the website if the terminal isn't your happy place yet.  
- __Link__: Create a pull link for students with nbgitpuller. **Share!**

### Slide 14

Group of people with dark skin tones dancing outside to the song Watch me (Whip/Nae nae) in front of a abstract mural. The text "WATCH ME DIFF WATCH ME REBASE" has been added above them.

### Slide 15

Screenshot of nbgitpuller interface filled out for the Statdew Valley activity. Relevant text on slide 16.
